version: '3'  
services:
  surls:
    env_file:
      - .env.docker
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: surls-container
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: always