version: '3'  
services:
  surls:
    env_file:
      - .env.docker.app
    stdin_open: true
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: surls-container
    ports:
      - "3000:3000"
    restart: always