version: '3'
services:
  postgres:
    env_file:
      - .env.docker.common
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  surls:
    env_file:
      - .env.docker.common
    stdin_open: true
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: surls-container
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres-data: